export const GET_PRODUCT_PROCESS = "GET_PRODUCT_PROCESS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"

export const DELETE_PRODUCT_PROCESS = "DELETE_PRODUCT_PROCESS"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

export const PUT_PRODUCT_PROCESS = "PUT_PRODUCT_PROCESS"
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS"
export const PUT_PRODUCT_ERROR = "PUT_PRODUCT_ERROR"